### ISSUE TITLE
REQUEST_URI instead of PATH_INFO

### ISSUE THREAD

**Issue by Dobatymo** [pklaus/wsgi-request-logger#13]
`              environ.get('PATH_INFO', ''),`
should use REQUEST_URI.
1) path_info does not include the query string, which is normally included in NCSA logs like apache
2) applications like werkzeug.wsgi.DispatcherMiddleware modify PATH_INFO and will lead to wrong logged values

**Comment by Miserlou** [comment]
Bump! Would love to see this fixed for: https://github.com/Miserlou/Zappa/issues/1048
