### ISSUE TITLE
Request time accuracy to low

### ISSUE THREAD

**Issue by haufes** [pklaus/wsgi-request-logger#3]
The times for my request are not correct. I have many request that are being log as taking no time. I see that the timer is using time.clock(). Apparently it's accuracy is not very good.

http://stackoverflow.com/questions/85451/python-time-clock-vs-time-time-accuracy

time.time() would be a better method to use.

**Comment by pklaus** [comment]
Thanks. I agree. But it seems that with Python v3.3 `time.time()`'s use is now deprecated. Instead, `time.process_time()` or `time.perf_counter()` should be used. I need to give it some thought. If you have a quick fix, fell free to provide my with a patch or pull request.

**Comment by haufes** [comment]
I'm in python2.7. Is time.time() deprecated in 3.3? I didn't see that in the docs.

If so, what I would do is abstract the time call in __call__ and have the init test what runtime is being used and set the method that will be called for the timer.

**Comment by pklaus** [comment]
Oops, yes, you're right. It's not `time.time()` that's deprecated but [`time.clock()`](https://docs.python.org/3/library/time.html#time.clock) and thus [the one being currently used to calculcate the runtime in wsgi-request-logger](https://github.com/pklaus/wsgi-request-logger/blob/6e34cf0/requestlogger/__init__.py#L33).
Should the runtime of the script stand for actual time passed or for the CPU time spent on the process?

**Comment by haufes** [comment]
I would think time passed, if it's just the process you would miss anything that is offloaded to an other process.  As well in my system time.time is giving me 6 decimal places where as time.clock is only 3. I have a lot of calls that are reported to be 0ms

**Comment by pklaus** [comment]
In 963b2e7 I fixed this now. The updated version 0.4.3 is on PyPI. You can install it with

    pip install --upgrade wsgi-request-logger

(I'm now using `time.perf_counter()` where it's available and `time.time()` as a backup. The actual time passed is what you want as this is the one related to user experience on your web site. If you want to benchmark CPU time spend on the script you would have to use Python 3.3+ and use `[https://docs.python.org/3/library/time.html#time.process_time](time.process_time()` as clock.)
