### ISSUE TITLE
allow to set self.logger.propagate=False

### ISSUE THREAD

**Issue by schlitzered** [pklaus/wsgi-request-logger#7]
hey, 

first thank you for this small handy package.

second:

could you please add a parameter to WSGILogger called "propergate" that accepts True/False, and pass this parameter to self.logger.propagate?

with this i can disable the default logger, because i do not like to get spammed on stdout, when i have a file appender enabled.

Thank You,

Stephan

**Comment by schlitzered** [comment]
just created a pull request ;-)

**Comment by pklaus** [comment]
Thanks for reminding me (by mail). I merged the commit and published an updated version on PyPI.
Note that I changed the doc string of the module back to triple quotes in d1f8d8a. I suppose your change to quadruple & quintuple quotes was unintended?

**Comment by schlitzered** [comment]
thanks, yes the change of these quotes was unintended :-)
